### ISSUE TITLE
[BUG] Issue: Error launching app

### ISSUE THREAD

**Issue by mashwishi** [lukechu10/Minecraft-Box-Launcher#312]
**Describe the bug**
Unable to find electron app.
Screenshot: http://prntscr.com/sqtv4j

**Comment by lukechu10** [comment]
Hello, are you sure you ran `npm prod` to build all the files using `webpack` before running `npm start`. That should explain why the files are not there.

Thanks!

**Comment by lukechu10** [comment]
I am going to close this issue for now. If you still encounter a problem launching the application, feel free to reopen the issue.

**Comment by failsafe42** [comment]
I am having the same issue and `npm prod` isn't recognized as a command.
Output of `npm prod`:
`$ npm prod

Usage: npm <command>

where <command> is one of:
    access, adduser, audit, bin, bugs, c, cache, ci, cit,
    clean-install, clean-install-test, completion, config,
    create, ddp, dedupe, deprecate, dist-tag, docs, doctor,
    edit, explore, fund, get, help, help-search, hook, i, init,
    install, install-ci-test, install-test, it, link, list, ln,
    login, logout, ls, org, outdated, owner, pack, ping, prefix,
    profile, prune, publish, rb, rebuild, repo, restart, root,
    run, run-script, s, se, search, set, shrinkwrap, star,
    stars, start, stop, t, team, test, token, tst, un,
    uninstall, unpublish, unstar, up, update, v, version, view,
    whoami

npm <command> -h  quick help on <command>
npm -l            display full usage info
npm help <term>   search for help on <term>
npm help npm      involved overview

Specify configs in the ini-formatted file:
    /home/josh/.npmrc
or on the command line via: npm <command> --key value
Config info can be viewed via: npm help config

npm@6.14.7 /usr/lib/node_modules/npm`

**Comment by lukechu10** [comment]
Sorry, it's `npm run prod`. My bad.
